// <auto-generated />
namespace MVCexample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class createTabMember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createTabMember));
        
        string IMigrationMetadata.Id
        {
            get { return "201910031005257_createTabMember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
